name: Terraform Conftest

on:
  pull_request:

jobs:
  validate:
    name: Validate Terraform Conftest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Run Terraform Conftest
        id: conftest
        uses: actionsforge/actions-terraform-conftest@v1.0.20
        with:
          conftest-version: 'v0.66.0'
          terraform-version: '1.6.0'
          policy-path: './policies'
          working-directory: './'
          run-terraform-test: 'true'
          run-terraform-plan: 'true'
          run-conftest: 'true'
          terraform-plan-file: 'plan.json'

      - name: Check results
        run: |
          echo "Plan file: ${{ steps.conftest.outputs.plan-file }}"
          echo "Passed: ${{ steps.conftest.outputs.conftest-passed }}"
          echo "Violations: ${{ steps.conftest.outputs.violations-count }}"
